language: cpp

compiler:
  - gcc
  - clang

sudo: false

# Handle git submodules yourself
git:
    submodules: false

before_script:
  - if [ "$TRAVIS_OS_NAME"=="linux" ] && [ "$CXX" == "g++" ]; then CXX_COMPILER=g++-${GCC_VERSION}; fi
  - if [ "$TRAVIS_OS_NAME"=="linux" ] && [ "$CXX" == "g++" ]; then C_COMPILER=gcc-${GCC_VERSION}; fi
  - if [ "$TRAVIS_OS_NAME"=="linux" ] && [ "$CXX" != "g++" ]; then CXX_COMPILER=clang++-${CLANG_VERSION}; fi
  - if [ "$TRAVIS_OS_NAME"=="linux" ] && [ "$CXX" != "g++" ]; then C_COMPILER=clang-${CLANG_VERSION}; fi
  - mkdir build
  - cd build
  - cmake --version
  - ${CXX_COMPILER} --version
  - ${C_COMPILER} --version
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_C_COMPILER=${C_COMPILER} ..

script: make && ctest

os:
  - linux

env:
  global:
    - GCC_VERSION="5"
    - CLANG_VERSION="3.7"
  matrix:
    - BUILD_TYPE=Debug
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    - boost-latest
    packages:
    - cmake
    - clang-3.7
    - libc++
    - g++-5
    - libboost1.55-all-dev
    - libeigen3-dev
