language: cpp

compiler:
  - gcc
  - clang

sudo: true

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-test-dev
  - mkdir build
  - cd build
  - cmake ..

script: make

os:
  - linux
  - osx

osx_image: xcode61
