language: cpp

compiler:
  - gcc
  - clang

sudo: true

before_script:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-${GCC_VERSION}; fi
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq gcc-${GCC_VERSION}; fi
  - if [ "$CXX" == "g++" ]; then sudo ln -s -v -f $(which g++-${GCC_VERSION}) /usr/bin/g++; fi
  - if [ "$CXX" == "g++" ]; then sudo ln -s -v -f $(which gcc-${GCC_VERSION}) /usr/bin/gcc; fi
  - sudo apt-get install -qq libboost-all-dev
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. --config ${BUILD_TYPE}

script: make && ctest

os:
  - linux

env:
  global:
    - GCC_VERSION="4.9"
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
